'use strict';

var mensajes = {

    error_db: "Error en base de datos, consulte con el administrador.",
    no_registrado: "Necesitas estar registrado.",
    ya_registrado: "Ya estás registrado.",
    logout: "Abandonaste correctamente la página.",
    pfg_asignado: "Ya tiene asignado un proyecto este curso.",
    pfgs_prop_min_tres: "Debe seleccionar tres proyectos.",
    pfgs_prop_distintos: "Debe seleccionar tres proyectos distintos.",
    pfgs_prop_repetidos: "Ya ha realizado su elección de proyectos propuestos.",
    pfgs_prop_asignados_ok: "Asignados los proyectos propuestos.",
    pfgs_prop_vacio: "No hay selecciones disponibles.",
    acceso_restringido: "Acceso restringido.",
    dni_repetido: 'El DNI ya existe.',
    profesor_tutoriza: 'El profesor tutoriza proyectos.',
    pertenece_comision: 'El profesor pertenece a la Comision.',
    pertenece_tribunal: 'El profesor pertenece a un Tribunal.',
    alumno_tiene_pfg: 'El alumno tiene asignado un PFG.',
    alumno_tiene_pfg_prop_asignados: 'El alumno tiene seleccionados PFGs propuestos.',
    no_permitido: 'No permitido.',
    usuario_actualizado: 'Usuario actualizado',
    password_distinta: 'La contraseña no coincide.',
    logout_passwd_actualizada: 'Constraseña actualizada: vuelva a entrar en la página',
    usuario_tiene_pfg: 'El usuario tiene asignado PFGs.',
    pertenece_comision_o_tribunal: 'El usuario pertenece a alguna comisión o tribunal.',
    usuario_borrado: 'Usuario borrado correctamente',
    alta_plantilla: "Plantilla dada de alta.",
    pesos_menor_cero: "Los pesos deben ser mayores que 0",
    pesos_mayor_cien: "Los pesos deben ser menores que 100",
    pesos_suma_no_cien: "La suma de los pesos debe ser igual a 100.",
    plantilla_rubrica_borrada: "La plantilla de rubrica se ha borrado.",
    plantilla_no_encontrada: "La plantilla de rubrica no se ha encontrado.",
    no_anadir_a_criterio: "No se puede añadir a criterios.",
    no_anadir_secciones_a_criterio: "No se puede añadir secciones a criterios.",
    no_anadir_criterio_a_secciones: "No se puede añadir criterios a una seccion con subsecciones.",
    error_entrada: "Error en parametros.",
    alta_secciones: "Realizada alta de secciones.",
    seccion_editada: "Realizada actualización de sección.",
    secciones_editadas: "Realizada actualización de secciónes.",
    error_borrar_nodo_raiz: "No se puede borrar esa sección.",
    seccion_borrada: "La sección se ha borrado.",
    criterio_borrado: "El criterio se ha borrado.",
    no_alumnos: "No hay alumnos disponibles.",
    no_profesores: "No hay alumnos disponibles.",
    cod_prop_repe: "Código de PFG propuesto repetido.",
    alta_pfg: "Alta de nuevo PFG. Asignada su rúbrica.",
    modificar_pfg: "PFG modificado.",
    pfg_borrado: "PFG borrado junto con su rúbrica.",
    pfg_con_selecciones: "El PFG tienen propuestas de seleccion por parte de alumnos. Debe asignarlo como PFG propuesto.",
    pfg_prop_asignado: "Se ha asignado el PFG al alumno.",
    modificar_tribunal: "Tribunal modificado.",
    miembros_repes_tribunal: "No se pueden repetir los componentes de un tribunal.",
    modificar_comision: "Comisión modificada",
    miembros_repes_comision: "No se pueden repetir los componentes de una comisión",
    curso_unico: "No es posible borrar el curso. Sólo un curso registrado.",
    alta_curso: "Nuevo curso dado de alta.",
    baja_curso: "Curso actual borrado."
};

module.exports = mensajes;